### ISSUE TITLE
Vagrant Up issue, post VirtualBox installation (ub1404)

### ISSUE THREAD

**Issue by snaex** [rapid7/metasploitable3#253]
## Issue Description
I initially got past this stage and was advised by the installation to add Hyper V as it is turned off, rebooted. Executed: 'vagrant up' once again and this happened. 

I have tried:
- removing the box from vagrant list
- followed by vagrant destroy
- reboot, don't know if that helps
- then adding the box again
- vagrant up and the same error

## Host System
* OS: Windows 10 v1709 (OS Build 16299.309)
* Packer Version: 1.1.1
* Vagrant Version: 1.9.2
* VirtualBox Version: 5.0.10 (script replaces my version 5.2.8)

## Command Output
```
Bringing machine 'ub1404' up with 'virtualbox' provider...
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> ub1404: Box 'metasploitable3-ub1404' could not be found. Attempting to find and install...
    ub1404: Box Provider: virtualbox
    ub1404: Box Version: >= 0
vagrant : E:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split': bad URI(is not URI?): file:///E:/Images/04 Metasploitable/metasploitable3/packer/builds/metasploitable3-ub1404 
(URI::InvalidURIError)
At line:1 char:1
+ vagrant up
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (E:/HashiCorp/Va...nvalidURIError):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
	from E:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
	from E:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/box_add.rb:475:in `metadata_url?'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/box_add.rb:81:in `block in call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/box_add.rb:79:in `map'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/box_add.rb:79:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:34:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builder.rb:116:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/util/busy.rb:19:in `busy'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/runner.rb:66:in `run'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/handle_box.rb:82:in `handle_box'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/handle_box.rb:36:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:34:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:34:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:34:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builder.rb:116:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/util/busy.rb:19:in `busy'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/runner.rb:66:in `run'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:34:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/warden.rb:34:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/builder.rb:116:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/util/busy.rb:19:in `busy'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/action/runner.rb:66:in `run'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/machine.rb:225:in `action_raw'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/machine.rb:200:in `block in action'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/environment.rb:567:in `lock'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/machine.rb:186:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/machine.rb:186:in `action'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
	from E:/HashiCorp/Vagrant/embedded/gems/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'

```

**Comment by Chan9390** [comment]
Hey, what is the output of `vagrant box list` ?

**Comment by secdecmso** [comment]
hello same problem here please help

**Comment by Chan9390** [comment]
Hey folks,

This is a ruby bug on Windows. It is mentioned in the [General Issues - Windows section](https://github.com/rapid7/metasploitable3/wiki/General-Issues#windows-10):

> **Ruby bug:** *Absolute path for vagrant home directory should not contain any spaces.* If you have a space in your system username, please change your vagrant home directory by altering the `VAGRANT_HOME` environment variable.

In the above error logs, there is a space in `04 Metasploitable`.

To resolve this issue,
- Move the vagrant home dir to an other folder without any spaces (the absolute path for vagrant home directory should not contains any spaces, as mentioned in the error message).
- (optional) Set the `VAGRANT_HOME` env var to the new path.
