### ISSUE TITLE
Error adding box to vagrant

### ISSUE THREAD

**Issue by d3viLc0d3r** [rapid7/metasploitable3#270]
## Issue Description
After successfully building the box using packer, when it attempt add box to vagrant it throws an error  "Error adding box to vagrant".

## Host System
* OS: Windows 8.1
* Packer Version: 1.2.2
* Vagrant Version: 1.9.1
* VirtualBox Version: 5.2.8

## Command Output
```
==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: C:\Users\Naveen Bisht\Downloads\m
etasploitable3\packer\templates/../builds/windows_2008_r2_virtualbox_0.1.0.box
Box successfully built by Packer.
Attempting to add the box to Vagrant...
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split': bad URI(is not URI?): file:///C:/Users/Naveen Bisht/Downloads/metasploitable3/packer/builds/windows_2008_r2_virtualbox.box (URI::InvalidURIError)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/box_add.rb:471:in `metadata_url?'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/box_add.rb:81:in `block in call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/box_add.rb:79:in `map'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/box_add.rb:79:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/box/command/add.rb:78:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/box/command/root.rb:66:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:308:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant:127:in `<main>'
Error adding box to Vagrant. See the above output for any error messages.
At C:\Users\Naveen Bisht\Downloads\metasploitable3\build_win2008.ps1:127 char:9
+         throw "Error adding box to Vagrant. See the above output for anyerror m ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Error adding bo...error messages.:String) [], RuntimeException
+ FullyQualifiedErrorId : Error adding box to Vagrant. See the above output for any error messages.
```

**Comment by Chan9390** [comment]
Hey @d3viLc0d3r , its a ruby bug on Windows. It is mentioned in the [General Issues - Windows section](https://github.com/rapid7/metasploitable3/wiki/General-Issues#windows-10):

> **Ruby bug:** *Absolute path for vagrant home directory should not contain any spaces.* If you have a space in your system username, please change your vagrant home directory by altering the VAGRANT_HOME environment variable. 

From the error logs, I can see that your username is `Naveen Bisht` which has a space in it. 

Solution:
- Move the vagrant home dir to an other folder without any spaces (the absolute path for vagrant home directory should not contains any spaces, as mentioned in the error message).
- (optional) Set the VAGRANT_HOME env var to the new path.

**Comment by Chan9390** [comment]
Same as issue #253

**Comment by d3viLc0d3r** [comment]
Thank You xD
