### ISSUE TITLE
`require': cannot load such file -- winrm (LoadError)

### ISSUE THREAD

**Issue by dmitvitalii** [rapid7/metasploitable3#378]
The issue #224  still persists.

## Host System
* OS: Fedora 29
* Vagrant Version: 2.1.2

## Command Output
```
Traceback (most recent call last):
	25: from /usr/share/vagrant/gems/bin/vagrant:23:in `<main>'
	24: from /usr/share/vagrant/gems/bin/vagrant:23:in `load'
	23: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/bin/vagrant:161:in `<top (required)>'
	22: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/environment.rb:275:in `cli'
	21: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/cli.rb:54:in `execute'
	20: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/commands/up/command.rb:87:in `execute'
	19: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	18: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/plugin/v2/command.rb:186:in `each'
	17: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	16: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	15: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/environment.rb:700:in `machine'
	14: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/vagrantfile.rb:79:in `machine'
	13: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/vagrantfile.rb:79:in `new'
	12: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/machine.rb:141:in `initialize'
	11: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/machine.rb:260:in `communicate'
	10: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/registry.rb:27:in `get'
	 9: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/communicators/winrm/plugin.rb:15:in `block in <class:Plugin>'
	 8: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/communicators/winrm/communicator.rb:6:in `<top (required)>'
	 5: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/communicators/winrm/communicator.rb:6:in `require_relative'
	 4: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/communicators/winrm/shell.rb:8:in `<top (required)>'
	 3: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/util/silence_warnings.rb:8:in `silence!'
	 2: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/communicators/winrm/shell.rb:9:in `block in <top (required)>'
	 1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- winrm (LoadError)
```

`$ vagrant plugin install winrm winrm-fs`  didn't help.

**Comment by jmartin-r7** [comment]
Unfortunately, as per the stack trace, this is an issue with vagrant and the gems installed in the local environment, not something within the control of this project.

I would suggest updating to the latest version of vagrant and it's plugins and trying again.  As of this comment vagrant latest version is `2.2.4`.

Closing as this is not an issue in the metasploitable3 project code.

**Comment by ljw416** [comment]
After upgrading the vagrant version, my problem solved. Thanks!

**Comment by thomasericdean** [comment]
On a fresh kali install as of 3/31/2021 I fixed this with:`sudo gem install winrm`. Then another error and I had to run `sudo gem install winrm-fs` . Then success.

**Comment by david-drinn** [comment]
`sudo gem install winrm-elevated` is the next one needed for me.

**Comment by h3x0v3rl0rd** [comment]
sudo gem install winrm
sudo gem install winrm-fs  
sudo gem install winrm-elevated

**Comment by pauloxm** [comment]
I'm doing the same to solve my problem, thanks @c0d3cr4f73r
