### ISSUE TITLE
undefined method `deprecation_warning' for Thor:Class (NoMethodError)

### ISSUE THREAD

**Issue by kity-linuxero** [rapid7/metasploitable3#433]
## Issue Description
I can't build w2008r2. I tried in severals platforms.

## Host System
* OS: Ubuntu 18.04 / Ubuntu 19.10 / Windows 10 1803
* Packer Version: v1.4.5 / v1.4.5 / v.1.4.5
* Vagrant Version: 2.2.6 / 2.2.6 / 2.2.6
* VirtualBox Version: 5.23 / 6.0.14 r133895 / 6.1.0 r135406 

## Command Output
```console
    virtualbox-iso: C:\Users\vagrant>C:\tools\ruby23\bin\rails.bat _4.1.1_ new "C:\Program Files\Rails_Server"
==> virtualbox-iso: C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-1.0.0/lib/thor/parser/option.rb:140:in `validate_default_type!': undefined method `deprecation_warning' for Thor:Class (NoMethodError)
==> virtualbox-iso: Did you mean?  deprecate_constant
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-1.0.0/lib/thor/parser/option.rb:115:in `validate!'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-1.0.0/lib/thor/parser/argument.rb:24:in `initialize'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-1.0.0/lib/thor/parser/option.rb:11:in `initialize'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-1.0.0/lib/thor/base.rb:582:in `new'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-1.0.0/lib/thor/base.rb:582:in `build_option'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/thor-1.0.0/lib/thor/base.rb:304:in `class_option'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/base.rb:202:in `class_option'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/app_base.rb:71:in `add_shared_options_for'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/rails/app/app_generator.rb:150:in `<class:AppGenerator>'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/rails/app/app_generator.rb:149:in `<module:Generators>'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/rails/app/app_generator.rb:143:in `<module:Rails>'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/generators/rails/app/app_generator.rb:3:in `<top (required)>'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/commands/application.rb:2:in `<top (required)>'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/lib/rails/cli.rb:14:in `<top (required)>'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
==> virtualbox-iso: 	from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.1.1/bin/rails:9:in `<top (required)>'
==> virtualbox-iso: 	from C:/tools/ruby23/bin/rails:22:in `load'
==> virtualbox-iso: 	from C:/tools/ruby23/bin/rails:22:in `<main>'
==> virtualbox-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
Error building the Vagrant boxes using Packer. Please check the output above for any error messages.
```

**Comment by jmartin-r7** [comment]
Automation tests are passing and built successfully for `vmware` and `virtualbox` on 12 January, 2020. 

Testing automation used:
Packer: `1.3.4`
VirtualBox `6.0.8`
Vagrant `2.2.4`

I will run additional validation on latest versions soon.

**Comment by jmartin-r7** [comment]
Closing, #562 updated and tested `vmware` and `virtualbox` platforms no current supported versions.
