### ISSUE TITLE
Vagrant up fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by lambdajack** [rapid7/metasploitable3#568]
## Issue Description
Linux installation instructions using vagrant fails.

Attempted to run on a completely fresh install of Ubuntu 22.04 Jammy Jellyfish which has been fully updated; bare metal. Dependencies installed.

### Notes
1. Related issue #378
2. Related issue #224
3. Tried `vagrant plugin install winrm winrm-fs` - installation succeeded, however it did not resolve the issue:
 ```
$ vagrant plugin list
vagrant-libvirt (0.7.0, system)
winrm (2.3.6, global)
winrm-fs (1.3.5, global)
```
4. Tried `sudo gem install winrm` - installation succeeded, however it did not resolve the issue:
```
$ gem list | grep -e winrm -e vagrant
vagrant (2.2.19)
vagrant-libvirt (0.7.0)
vagrant_cloud (3.0.5)
winrm (2.3.6)
```

## Host System
* OS: Ubuntu 22.04 (Jammy Jellyfish)
* Packer Version: `1.8.0`
* Vagrant Version: `2.2.19`
* VirtualBox Version: `6.1.32_Ubuntu r149290`

## Command Output
```
$ mkdir metasploitable3-workspace
$ cd metasploitable3-workspace
$ curl -O https://raw.githubusercontent.com/rapid7/metasploitable3/master/Vagrantfile && vagrant up
```  
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2297  100  2297    0     0   4725      0 --:--:-- --:--:-- --:--:--  4726
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- winrm (LoadError)
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/plugins/communicators/winrm/shell.rb:9:in `block in <top (required)>'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/util/silence_warnings.rb:8:in `silence!'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/plugins/communicators/winrm/shell.rb:8:in `<top (required)>'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/plugins/communicators/winrm/communicator.rb:6:in `require_relative'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/plugins/communicators/winrm/communicator.rb:6:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/plugins/communicators/winrm/plugin.rb:15:in `block in <class:Plugin>'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/registry.rb:27:in `get'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:267:in `communicate'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:149:in `initialize'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/vagrantfile.rb:81:in `new'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/vagrantfile.rb:81:in `machine'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/environment.rb:716:in `machine'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:186:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/plugins/commands/up/command.rb:87:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/cli.rb:67:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/environment.rb:290:in `cli'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/bin/vagrant:226:in `<top (required)>'
	from /usr/bin/vagrant:25:in `load'
	from /usr/bin/vagrant:25:in `<main>'
```

**Comment by theyough** [comment]
try to install `vagrant plugin install winrm-elevated` it works for me

**Comment by jmartin-r7** [comment]
This seems to be a vagrant issue not controlled by this project.

Plugins available to the vagrant environment are managed by vagrant. The recommendation above to install additional vagrant plugins may be a viable solution. Without this extra plugin can you load other windows vagrant boxes when utilizing `winrm` in the `Vagrantfile`?
