### ISSUE TITLE
how fix it

### ISSUE THREAD

**Issue by FaLC0N-x** [rapid7/metasploitable3#587]
## Issue Description
**Please check the [General Issues](https://github.com/rapid7/metasploitable3/wiki/General-Issues) section in the wiki before you submit the issue.**
If you didn't find your issue mentioned, please give a thorough description of the issue you're seeing.
Also, please be sure to include any troubleshooting steps that you've already attempted.

## Host System
* OS:kali linux
* Packer Version:
* Vagrant Version:
* VirtualBox Version:

## Command Output
Copy the relevant command output here.
If it's long, either post to a gist and add the link here, or isolate the error lines.
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- winrm-elevated (LoadError)
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/communicators/winrm/shell.rb:12:in `<top (required)>'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/communicators/winrm/communicator.rb:6:in `require_relative'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/communicators/winrm/communicator.rb:6:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/communicators/winrm/plugin.rb:15:in `block in <class:Plugin>'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/registry.rb:27:in `get'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/machine.rb:269:in `communicate'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/machine.rb:151:in `initialize'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/vagrantfile.rb:83:in `new'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/vagrantfile.rb:83:in `machine'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/environment.rb:740:in `machine'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/plugin/v2/command.rb:186:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/commands/up/command.rb:87:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/cli.rb:67:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/environment.rb:301:in `cli'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/bin/vagrant:243:in `<top (required)>'
	from /usr/bin/vagrant:25:in `load'
	from /usr/bin/vagrant:25:in `<main>'

**Comment by gwillcox-r7** [comment]
Not enough information is available to replicate this issue. Please provide more information on what steps you took to cause this to happen.

**Comment by jmartin-r7** [comment]
Likely you are missing a required vagrant plugin:
```
vagrant plugin install winrm-elevated
```
